### ISSUE TITLE
What is the difference between 3d lmks and 2d lmks?

### ISSUE THREAD

**Issue by SavvaI** [HavenFeng/photometric_optimization#5]
Hi!
From the code, it is not clear what is the difference between 3d lmks and 2d lmks? Both have 68 points and both have an effective dimension of 3. As I can judge from the code, 3d lmks are only used for visualization. But what is the actual difference between them, and why 2dlmks have the prefix "2d" even if they are actually 3d? 
Thanks

**Comment by HavenFeng** [comment]
Hi, so the 3d lmks are the 68 lmks with fixed jaw contour for visualization while the 2d lmks is the one used for the optimization with dynamic changing jaw contour (it's a function of head rotation angles). The 3 dimensions of 2d lmks are x,y,z in the image plane coordinates, since it's aligned to the input image landmark ground truth, the z value is ignored.
